branch-defaults:
  default:
    environment: tuta17-udagram-api-dev
    group_suffix: null
global:
  application_name: tuta17-udagram-api
  branch: null
  default_ec2_keyname: mykeypair
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
